### ISSUE TITLE
Suggestion: Record admins steamid

### ISSUE THREAD

**Issue by jljr222** [casual-trade-and-fun-server/Threaded-MySQL-Bans#1]
It would be great if you could also record the admins steam id as well. If it's Console then it could just be blank, but that way there is an easier way to tie back who banned the person, specifically if the admins on your server change names frequently it's easy to see who it was :)

**Comment by ShadowMen** [comment]
Great idea! I'm on it :+1:

**Comment by jljr222** [comment]
Thanks!
