### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jljr222** [casual-trade-and-fun-server/Threaded-MySQL-Bans#2]
Sorry, I've noticed I'm getting this a lot in my error logs after your last change :(

L 02/09/2016 - 14:57:23: [SM] Native "Database.Escape" reported: Invalid database Handle 1018 (error: 4)
L 02/09/2016 - 14:57:23: [SM] Displaying call stack trace for plugin "mysqlt_bans.smx":
L 02/09/2016 - 14:57:23: [SM]   [0]  Line 221, /groups/sourcemod/upload_tmp/textD2FbaD.sp::CheckBanStateOfClient()
L 02/09/2016 - 14:57:23: [SM]   [1]  Line 208, /groups/sourcemod/upload_tmp/textD2FbaD.sp::OnClientPostAdminCheck()
L 02/09/2016 - 14:57:25: Error log file session closed.
L 02/09/2016 - 14:57:31: SourceMod error session started

**Comment by ShadowMen** [comment]
I'm working on it, but have to wait until weekend when I have time

**Comment by jljr222** [comment]
No worries :)

**Comment by jljr222** [comment]
Actually I have a different error using your latest version, didn't realize you made another change:

L 02/11/2016 - 04:29:23: [mysqlt_bans.smx] [MYBans] Error during table update: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'admin_steam_id' at line 1
L 02/11/2016 - 04:29:32: [SM] Native "Database.Escape" reported: Invalid database Handle 1018 (error: 4)
L 02/11/2016 - 04:29:32: [SM] Displaying call stack trace for plugin "mysqlt_bans.smx":
L 02/11/2016 - 04:29:32: [SM]   [0]  Line 71, E:\Website\Bor3d Gaming\servers\SourceMod 1.7.3 (Windows)\addons\sourcemod\scripting\include\bans.inc::CheckBanStateOfClient()
L 02/11/2016 - 04:29:32: [SM]   [1]  Line 67, E:\Website\Bor3d Gaming\servers\SourceMod 1.7.3 (Windows)\addons\sourcemod\scripting\mysqlt_bans.sp::OnClientPostAdminCheck()

I would check to see if you're setting up the database table correctly. Looks like it doesn't know how to handle making changes if the database doesn't exist already.
